server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: localhost:29092
    topic: transactions
    group-id: financial-transactions
    auto-offset-reset: earliest
  datasource:
    url: jdbc:postgresql://localhost:5432/financial
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



