server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    topic: transactions
    group-id: financial-transactions
    auto-offset-reset: earliest
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/financial
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect